/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fetchingdataintable;

import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PMYLS
 */
public class fetchingTable extends javax.swing.JFrame {

    Connection con;
    public fetchingTable() {
        initComponents();
//        
//        setBackground(new Color(0,0,0,0));
//        dbTable.getTableHeader().setFont(new Font("Seoge UI", Font.BOLD,14));
////        dbTable.getTableHeader().setOpaque();
//        dbTable.getTableHeader().setBackground(new Color(0,67,70));
//        dbTable.getTableHeader().setForeground(new Color(255,255,255));
        String url = "jdbc:mysql://localhost/hms";
        String user = "root";
        String pass = "";
        
        try{
            con = DriverManager.getConnection(url, user, pass); 
        }
        catch(Exception ex){
        System.out.println("Error");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dbTable = new javax.swing.JTable();
        show = new java.awt.Button();
        clear = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dbTable.setBackground(new java.awt.Color(0, 67, 70));
        dbTable.setForeground(new java.awt.Color(255, 255, 255));
        dbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "S:No", "Doctor Name", "Doctor Category"
            }
        ));
        dbTable.setGridColor(new java.awt.Color(255, 255, 255));
        dbTable.setRowHeight(25);
        dbTable.setSelectionBackground(new java.awt.Color(0, 192, 182));
        dbTable.setSelectionForeground(new java.awt.Color(0, 67, 70));
        dbTable.setShowGrid(true);
        dbTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(dbTable);

        show.setBackground(new java.awt.Color(0, 67, 70));
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setLabel("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(0, 67, 70));
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setLabel("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        String sql = "SELECT * FROM doctortable";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rst = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) dbTable.getModel();
            model.setRowCount(0);
            while(rst.next()){
                model.addRow(new Object[] {rst.getString(1),rst.getString(2), rst.getString(3)});
            }
        } catch(Exception e){}
        System.out.println("Error");
    }//GEN-LAST:event_showActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        DefaultTableModel model = (DefaultTableModel) dbTable.getModel();
        model.setRowCount(0);
        model.setRowCount(4);
        
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fetchingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fetchingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fetchingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fetchingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fetchingTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button clear;
    private javax.swing.JTable dbTable;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Button show;
    // End of variables declaration//GEN-END:variables
}
